# Generated by Django 5.0.1 on 2024-04-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
