# Generated by Django 5.0.1 on 2024-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0004_chatroom_chatroommember_chatroom_members_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
